services:
  db:
    container_name: container-db
    image: postgres:12.3-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    container_name: container-api
    build:
      context: ./api
      args:
        WORKDIR: $WORKDIR
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      API_DOMAIN: "localhost:$FRONT_PORT"
    volumes:
      - ./api:/$WORKDIR
    depends_on:
      - db
    ports:
      - "$API_PORT:$CONTAINER_PORT"

  spa:
    container_name: container-spa
    build:
      context: ./spa
    volumes:
      - ./spa:/app:cached
      - nuxt_node_modules:/app/node_modules
    ports:
      - "8080:3000"
      - "24678:24678"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=8080
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn && yarn dev"
volumes:
  nuxt_node_modules:

  # front:
  #   build:
  #     context: ./front
  #     args:
  #       WORKDIR: $WORKDIR
  #       CONTAINER_PORT: $CONTAINER_PORT
  #       API_URL: "http://localhost:$API_PORT/api/v1"
  #   command: yarn run dev
  #   volumes:
  #     - ./front:/$WORKDIR
  #   ports:
  #     - "$FRONT_PORT:$CONTAINER_PORT"
  #   depends_on:
  #     - api